"""Manufacturing package for the A0.2 carrier (KiCad 10 python + kicad-cli). Release review, Gerber pass.

Writes outputs/fab-a02/:
  gerbers/          F.Cu, In1.Cu, In2.Cu, B.Cu, paste, silk (mask subtracted), mask, Edge.Cuts, Gerber X2 with
                    netlist attributes, plus the .gbrjob stackup (4 layers, 1.6 mm, 1 oz on every layer)
  drill/            Excellon, plated and non-plated holes in separate files, Gerber X2 drill maps
  KINO_D4_Carrier_A0_2-gerbers.zip   gerbers/ and drill/ together, for upload
  CPL-A02.csv       placement as KiCad writes it, both sides, mm, DNP left out; fiducials, test lands and holes
                    are excluded by their footprint attributes; the hand-fit sockets are left out.
  CPL-A02-JLC.csv   the same rows under the assembler's column names (Designator, Mid X, Mid Y, Layer, Rotation).
                    Rotations are KiCad's: check them in the assembler's preview. Through-hole origins are pin 1.
  BOM-A02-FAB.csv   one line per part number: quantity, designators, footprint, manufacturer part, LCSC number
                    where part_selection.json gives one for that same part number. Lines come from the board's BOM
                    attributes (no test lands, holes, pogo field or fiducials) and leave out DNP parts.
  BOM-A02-HANDFIT.csv  the XIAO sockets J200-J500: two 1x07 sockets per position (8 in all), fitted by hand after
                    assembly, so they are in neither the BOM above nor the placement files.
  FAB-NOTES.txt     the order options and assembly notes that must travel with the files (ODD JOBS 178).
Run after the final DRC (zones refilled). The board file is read, never saved.
"""
import csv, json, shutil, subprocess, zipfile
from collections import OrderedDict
from pathlib import Path
import pcbnew as pcb
from rework import ROOT, TARGET
from build import _KS

CLI = next(p for p in (_KS.parent / 'MacOS/kicad-cli', _KS.parent.parent / 'bin/kicad-cli', Path('kicad-cli')) if p.exists() or p.name == 'kicad-cli')
OUT = ROOT / 'outputs/fab-a02'
LAYERS = 'F.Cu,In1.Cu,In2.Cu,B.Cu,F.Paste,B.Paste,F.SilkS,B.SilkS,F.Mask,B.Mask,Edge.Cuts'
HANDFIT = {'J200': 2, 'J300': 2, 'J400': 2, 'J500': 2}      # two 1x07 sockets per XIAO position

NOTES = """KINO D4 carrier A0.2 - fabrication and assembly notes (generated by design/fab_a02.py)
Release review: hardware/pcb/kino-d4-carrier-a0/A02-RELEASE.md

BOARD
- 4 layers, FR-4, 1.6 mm, 117.01 x 69.41 mm. Layer order L1 F.Cu, L2 In1.Cu (GND plane), L3 In2.Cu, L4 B.Cu.
- Copper 1 oz (35 um) on ALL FOUR layers. Inner 1 oz is required (SYS_RAW battery path on In2); it is not the
  default inner weight at most fabs.
- ENIG, black solder mask, white legend. No impedance control.
- Minimum via 0.3 mm drill / 0.6 mm pad; seven 0.2 mm thermal vias inside the U701 and U1201 exposed pads.
- Vias tented both sides, no plugging. Via-in-pad left unplugged on purpose: U700 exposed pad (one 0.3 mm via),
  U701 and U1201 exposed pads (footprint thermal vias). Order epoxy fill + cap only if voiding must be avoided.
- No order-number placeholder: choose "remove order number", or specify a location (S/N box, front bottom).
- Panel: add 5 mm rails on the long edges if the assembler needs them; J1000 (USB-C) sits at the south edge and
  R702 0.29 mm from the edge, so keep tabs or V-score away from the south-east corner.

ASSEMBLY
- Both sides. Reflow the top (front, 67 parts) first, then the bottom (155 parts, incl. L1200 XAL7070,
  L1100 and the SMA diodes) so the heavy parts are upright in the last reflow.
- Through-hole, after reflow: J1100 (front); J100, J101, J201-J501 (back); XIAO sockets J200-J500 by hand
  (BOM-A02-HANDFIT.csv: two 1x07 sockets per position, 8 in all).
- Solid GND connections on through-hole pins (need more heat): J1100.3, J300.13, J201.1, J501.1.
- Fiducials: FID1-3 on the front, FID4-6 on the back (1 mm copper, 2 mm mask opening).
- Placement file: KiCad rotations. Check every polarised part and pin 1 in the assembler preview, bottom side
  mirrored: SOT-23/SOT-23-6/TSOT-23-8, SOIC-8, TSSOP/VSSOP, QFN/SON/LGA, SOD diodes, JST GH, USB-C.
  Through-hole origins are at pin 1.
- DNP: R605, R1110, C1201, J601 (their lands still receive paste).
- BOM lines without an LCSC number are ordered by the manufacturer part number: match or consign them.
- X-ray if offered: U1100 (VQFN-29, 0.4 mm), U1200, U1000, U800 (LGA-14), U700, U701, U1201, U802.
"""

def cli(*args):
    r = subprocess.run([str(CLI), *map(str, args)], capture_output=True, text=True)
    assert r.returncode == 0, (args, r.stdout, r.stderr)

if OUT.exists(): shutil.rmtree(OUT)
(OUT / 'gerbers').mkdir(parents=True); (OUT / 'drill').mkdir()
cli('pcb', 'export', 'gerbers', '--layers', LAYERS, '--subtract-soldermask', '-o', OUT / 'gerbers', TARGET)
cli('pcb', 'export', 'drill', '--format', 'excellon', '--excellon-separate-th', '--generate-map', '--map-format', 'gerberx2',
    '-u', 'mm', '-o', OUT / 'drill', TARGET)
cli('pcb', 'export', 'pos', '--side', 'both', '--format', 'csv', '--units', 'mm', '--exclude-dnp', '-o', OUT / 'CPL-A02.csv', TARGET)
rows = [r for r in csv.DictReader(open(OUT / 'CPL-A02.csv')) if r['Ref'] not in HANDFIT]
with open(OUT / 'CPL-A02.csv', 'w', newline='') as fh:
    w = csv.DictWriter(fh, fieldnames=['Ref', 'Val', 'Package', 'PosX', 'PosY', 'Rot', 'Side']); w.writeheader(); w.writerows(rows)
with open(OUT / 'CPL-A02-JLC.csv', 'w', newline='') as fh:
    w = csv.writer(fh); w.writerow(['Designator', 'Mid X', 'Mid Y', 'Layer', 'Rotation'])
    for r in rows: w.writerow([r['Ref'], r['PosX'] + 'mm', r['PosY'] + 'mm', 'Top' if r['Side'] == 'top' else 'Bottom', r['Rot']])
with zipfile.ZipFile(OUT / 'KINO_D4_Carrier_A0_2-gerbers.zip', 'w', zipfile.ZIP_DEFLATED) as z:
    for p in sorted((OUT / 'gerbers').iterdir()) + sorted((OUT / 'drill').iterdir()): z.write(p, p.name)

parts = {p['ref']: p for p in json.loads((ROOT / 'design/parts.json').read_text())}
lcsc = {}                                # only where the selection is the part number actually captured
for s in json.loads((ROOT / 'design/part_selection.json').read_text())['selections']:
    for r in s['refs']:
        if s.get('lcsc') and r in parts and s['mpn'] in parts[r]['mpn']: lcsc[r] = s['lcsc']
b = pcb.LoadBoard(str(TARGET))
lines = OrderedDict(); handfit = []
for f in sorted(b.GetFootprints(), key=lambda f: f.GetReference()):
    ref = f.GetReference()
    if f.IsExcludedFromBOM() or f.IsBoardOnly() or f.IsDNP() or ref not in parts or parts[ref]['dnp']: continue
    p = parts[ref]
    if ref in HANDFIT: handfit.append((ref, p)); continue
    key = (p['mpn'], p['value'], p['footprint'])
    line = lines.setdefault(key, {'refs': [], 'qty': 0, 'lcsc': set()})
    line['refs'].append(ref); line['qty'] += 1
    if ref in lcsc: line['lcsc'].add(lcsc[ref])
with open(OUT / 'BOM-A02-FAB.csv', 'w', newline='') as fh:
    w = csv.writer(fh)
    w.writerow(['Quantity', 'Comment', 'Designator', 'Footprint', 'Manufacturer Part', 'LCSC Part #'])
    for (mpn, value, fp), line in lines.items():
        w.writerow([line['qty'], value, ','.join(line['refs']), fp.split(':')[-1], mpn.replace('2 x ', ''), ';'.join(sorted(line['lcsc']))])
with open(OUT / 'BOM-A02-HANDFIT.csv', 'w', newline='') as fh:
    w = csv.writer(fh); w.writerow(['Quantity', 'Comment', 'Designator', 'Manufacturer Part', 'Fit'])
    w.writerow([sum(HANDFIT[r] for r, _ in handfit), handfit[0][1]['value'], ','.join(r for r, _ in handfit),
                handfit[0][1]['mpn'].replace('2 x ', ''), 'two 1x07 sockets per position, hand-soldered from the front after assembly'])
for (mpn, value, fp), line in lines.items():
    assert len(line['lcsc']) <= 1, ('more than one LCSC number on one BOM line', mpn, line)
(OUT / 'FAB-NOTES.txt').write_text(NOTES)
n_parts = sum(l['qty'] for l in lines.values())
print(f'fab-a02: gerbers {len(list((OUT / "gerbers").iterdir()))} files, drill {len(list((OUT / "drill").iterdir()))} files, '
      f'BOM {len(lines)} lines / {n_parts} parts', flush=True)
import os; os._exit(0)
