import type { DeviceRecipe } from './recipes';
import { RECIPE_SCHEMA } from './recipes';

// Factory looks. These ship on the camera and are never overwritten in
// place — editing one in KINO Studio produces a custom copy.

export const FACTORY_RECIPES: DeviceRecipe[] = [
  {
    schema: RECIPE_SCHEMA,
    id: 'party-neg',
    name: 'Party Neg',
    factory: true,
    description: 'Warm skin, cyan shadows, higher contrast. Default.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 86,
      exposureBias: 0,
      gainLimit: 16,
      denoise: 1,
      sharpness: 1,
    },
    look: {
      contrast: 1.08,
      saturation: 1.12,
      temperature: 180,
      tint: -2,
      blackPoint: 4,
      highlightCompression: 0.08,
      grain: 0.18,
      vignette: 0.05,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'chrome',
    name: 'Chrome',
    factory: true,
    description: 'Muted color, low saturation, controlled highlights.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 88,
      exposureBias: -0.3,
      gainLimit: 12,
      denoise: 1,
      sharpness: 1,
    },
    look: {
      contrast: 1.05,
      saturation: 0.82,
      temperature: -40,
      tint: 0,
      blackPoint: 6,
      highlightCompression: 0.16,
      grain: 0.1,
      vignette: 0.03,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'superia',
    name: 'Superia',
    factory: true,
    description: 'Strong greens, warm skin, visible grain.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 84,
      exposureBias: 0.3,
      gainLimit: 20,
      denoise: 0,
      sharpness: 1,
    },
    look: {
      contrast: 1.1,
      saturation: 1.25,
      temperature: 120,
      tint: 4,
      blackPoint: 3,
      highlightCompression: 0.06,
      grain: 0.28,
      vignette: 0.04,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'vivid',
    name: 'Vivid',
    factory: true,
    description: 'High saturation, strong primaries.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 88,
      exposureBias: 0,
      gainLimit: 14,
      denoise: 1,
      sharpness: 2,
    },
    look: {
      contrast: 1.18,
      saturation: 1.45,
      temperature: 0,
      tint: 0,
      blackPoint: 5,
      highlightCompression: 0.04,
      grain: 0.08,
      vignette: 0.06,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'mono',
    name: 'Mono',
    factory: true,
    description: 'High-contrast black and white, coarse grain.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 88,
      exposureBias: 0,
      gainLimit: 24,
      denoise: 0,
      sharpness: 2,
    },
    look: {
      contrast: 1.3,
      saturation: 0,
      temperature: 0,
      tint: 0,
      blackPoint: 12,
      highlightCompression: 0.05,
      grain: 0.35,
      vignette: 0.08,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'motion',
    name: 'Motion',
    factory: true,
    description: 'Longer exposure, low gain, motion blur.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 84,
      exposureBias: 0.7,
      gainLimit: 8,
      denoise: 1,
      sharpness: 0,
    },
    look: {
      contrast: 1.02,
      saturation: 1.05,
      temperature: 60,
      tint: 0,
      blackPoint: 2,
      highlightCompression: 0.12,
      grain: 0.15,
      vignette: 0.1,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'flash-digi',
    name: 'Flash Digi',
    factory: true,
    description: 'Sharp and bright, direct flash, highlights allowed to clip.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 88,
      exposureBias: 0.3,
      gainLimit: 20,
      denoise: 0,
      sharpness: 2,
    },
    look: {
      contrast: 1.15,
      saturation: 1.18,
      temperature: 40,
      tint: 0,
      blackPoint: 6,
      highlightCompression: 0.02,
      grain: 0.12,
      vignette: 0.02,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'warm-2007',
    name: 'Warm 2007',
    factory: true,
    description: 'Warm white balance, consumer-digicam color.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 86,
      exposureBias: 0,
      gainLimit: 16,
      denoise: 1,
      sharpness: 1,
    },
    look: {
      contrast: 1.06,
      saturation: 1.15,
      temperature: 260,
      tint: 3,
      blackPoint: 3,
      highlightCompression: 0.1,
      grain: 0.14,
      vignette: 0.04,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'cold-flash',
    name: 'Cold Flash',
    factory: true,
    description: 'Cool white balance, hard flash contrast.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 88,
      exposureBias: -0.3,
      gainLimit: 18,
      denoise: 0,
      sharpness: 2,
    },
    look: {
      contrast: 1.12,
      saturation: 0.95,
      temperature: -220,
      tint: -4,
      blackPoint: 6,
      highlightCompression: 0.05,
      grain: 0.16,
      vignette: 0.05,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'disposable',
    name: 'Disposable',
    factory: true,
    description: 'High contrast, heavy grain, strong vignette.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 80,
      exposureBias: 0.3,
      gainLimit: 24,
      denoise: 0,
      sharpness: 1,
    },
    look: {
      contrast: 1.22,
      saturation: 1.08,
      temperature: 90,
      tint: 5,
      blackPoint: 8,
      highlightCompression: 0.03,
      grain: 0.4,
      vignette: 0.18,
    },
  },
  {
    schema: RECIPE_SCHEMA,
    id: 'raw-digi',
    name: 'Raw Digi',
    factory: true,
    description: 'No processing beyond the sensor JPEG.',
    capture: {
      resolution: '1600x1200',
      jpegQuality: 90,
      exposureBias: 0,
      gainLimit: 16,
      denoise: 0,
      sharpness: 1,
    },
    look: {
      contrast: 1.0,
      saturation: 1.0,
      temperature: 0,
      tint: 0,
      blackPoint: 0,
      highlightCompression: 0,
      grain: 0,
      vignette: 0,
    },
  },
];

export function factoryRecipeById(id: string): DeviceRecipe | undefined {
  return FACTORY_RECIPES.find((r) => r.id === id);
}
