// KINO Twin §21: replay reconstructs a TwinSimulator session from a recorded
// `kino.sim-session` doc — the payoff of the determinism work in Tasks 3-7.
// It only ever drives `device.receive` with the recorded raw KDP 'in' bytes
// (plus the recorded fault-injection actions); recorded 'out' bytes are
// never fed anywhere — the device alone regenerates those, which is exactly
// what verifyReplay checks (§10/§20: no JSON side-channel around protocol
// behavior).
import { D4_V1 } from '@kino/hardware-profiles';
import type { ScenarioFlags } from '@kino/test-fixtures';
import { TwinSimulator } from './TwinSimulator';
import type { SimEvent } from './events';
import { base64ToBytes } from './recorder';
import type { SimSessionDoc, SimSessionEvent } from './recorder';

/**
 * How long `done` waits after the last scheduled entry before resolving.
 * Large enough to comfortably clear a normal command's 8-26 ms dispatch
 * latency (MockKinoDevice.handleFrame); small enough to stay well under
 * `startAmbient`'s 600 ms first log tick, so a short scripted session's
 * replay never picks up an ambient log/capture event the original recording
 * never saw. (A session that itself runs past 600 ms, or arms
 * `delayedResponses`, would need a wider margin — out of scope here.)
 */
const TRAILING_MARGIN_MS = 200;

/**
 * Builds a fresh TwinSimulator seeded like the original, feeds every
 * recorded 'in' + 'fault' entry back at its recorded `atMs` (scaled by
 * `speed`), and never replays 'out' entries — the device regenerates its own
 * outbound bytes from the same inputs. `done` resolves once every entry has
 * been delivered and its response has had time to land.
 */
export function replaySession(
  doc: SimSessionDoc,
  opts?: { speed?: number; onEvent?: (e: SimEvent) => void },
): { sim: TwinSimulator; done: Promise<void> } {
  const speed = opts?.speed ?? 1;
  const startEpochMs = Date.parse(doc.startedAtIso);
  const replayRealT0 = Date.now();

  const sim = new TwinSimulator({
    seed: doc.seed,
    // @kino/hardware-profiles has exactly one profile today (see
    // recorder.ts's own note) — doc.profile is informational, not a lookup
    // key, since there is nothing else in this codebase to resolve it to.
    profile: D4_V1,
    // KINO Twin §21: rebased so this fresh device's clock reads exactly what
    // the ORIGINAL recording's device read at the same point in the session
    // — `startEpochMs` right now, advancing in lockstep with real/fake time
    // after that — regardless of how much time has passed since the
    // original recording finished. Every scheduling delay in this engine
    // (dispatch latency, ambient ticks) is seed-derived, never now()-derived
    // (MockKinoDevice never reads `this.now()` to choose a setTimeout delay),
    // so this is the only clock rebasing replay needs for byte-identical
    // output, given the same seed and the same relative input timing below.
    now: () => startEpochMs + (Date.now() - replayRealT0),
  });

  if (opts?.onEvent) sim.onEvent(opts.onEvent);

  let lastAtMs = 0;
  const done = new Promise<void>((resolve) => {
    const deliver = (entry: Extract<SimSessionEvent, { kind: 'in' } | { kind: 'fault' }>) => {
      if (entry.kind === 'in') {
        sim.device.receive(base64ToBytes(entry.b64));
      } else if (entry.op === 'scenario') {
        sim.device.setScenario(entry.key as keyof ScenarioFlags, entry.value);
      } else {
        sim.device.setCamFault(entry.cam, entry.fault);
      }
    };

    for (const entry of doc.events) {
      if (entry.kind !== 'in' && entry.kind !== 'fault') continue; // 'out'/'sim' are never inputs — see the file header
      lastAtMs = Math.max(lastAtMs, entry.atMs);
      setTimeout(() => deliver(entry), entry.atMs / speed);
    }
    setTimeout(resolve, lastAtMs / speed + TRAILING_MARGIN_MS);
  });

  return { sim, done };
}

function bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

/**
 * Replays `doc` against a fresh device and byte-compares every regenerated
 * outbound frame against the recorded 'out' stream, in order. `ok: true`
 * means the recording is faithfully replayable; otherwise
 * `firstDivergenceAtMs` is the recorded `atMs` of the first 'out' entry that
 * no longer matches (or of the last recorded 'out' entry, if the replay
 * produced fewer frames than were recorded).
 */
export async function verifyReplay(doc: SimSessionDoc): Promise<{ ok: boolean; firstDivergenceAtMs: number | null }> {
  const recordedOut = doc.events.filter((e): e is Extract<SimSessionEvent, { kind: 'out' }> => e.kind === 'out');

  const regenerated: Uint8Array[] = [];
  const { sim, done } = replaySession(doc);
  // The only way regenerated bytes exist to compare at all — an unattached
  // device silently drops every write (MockKinoDevice.sendFrame: `if
  // (!this.sink) return;`). This never feeds the recorded 'out' bytes back
  // in; it only observes what the fresh device produces on its own.
  sim.device.attach(
    (bytes) => regenerated.push(bytes),
    () => {},
  );

  await done;
  sim.device.detach();
  sim.dispose();

  const count = Math.max(recordedOut.length, regenerated.length);
  for (let i = 0; i < count; i++) {
    const recordedEntry = recordedOut[i];
    const regen = regenerated[i];
    if (!recordedEntry || !regen || !bytesEqual(base64ToBytes(recordedEntry.b64), regen)) {
      const fallback = recordedOut[recordedOut.length - 1]?.atMs ?? 0;
      return { ok: false, firstDivergenceAtMs: recordedEntry?.atMs ?? fallback };
    }
  }
  return { ok: true, firstDivergenceAtMs: null };
}
