export {
  Button,
  ClassicProgressBar,
  CompactTable,
  Panel,
  StatusLamp,
  TabStrip,
  ToolbarFrame,
  UtilitySlider,
  tabIds,
  type ButtonProps,
  type PanelProps,
  type StatusLampState,
  type TabItem,
} from './primitives';
