// Rasterise a brand PNG to a 1-bit C array for the camera's boot screen.
//
// Run once and commit the result: the device has no image decoder and no
// font engine, and adding either to draw one static wordmark would be a lot
// of firmware for a picture that never changes.
import { pathToFileURL } from 'node:url';
import { readFileSync, writeFileSync } from 'node:fs';

const repo = 'c:/Users/AlexanderMoravcik/Desktop/kino d4';
const src = process.argv[2];
const out = process.argv[3];
const targetW = Number(process.argv[4] ?? 420);
const name = process.argv[5] ?? 'KINO_LOGO';

const pw = await import(pathToFileURL(repo + '/node_modules/playwright-core/index.js').href);
const { chromium } = pw.default ?? pw;
const browser = await chromium.launch();
const page = await browser.newPage();

const b64 = readFileSync(src).toString('base64');
const res = await page.evaluate(async ({ dataUrl, targetW }) => {
  const img = new Image();
  img.src = dataUrl;
  await img.decode();
  const scale = targetW / img.naturalWidth;
  const w = targetW;
  const h = Math.max(1, Math.round(img.naturalHeight * scale));
  const c = document.createElement('canvas');
  c.width = w; c.height = h;
  const g = c.getContext('2d');
  g.imageSmoothingEnabled = true;
  g.imageSmoothingQuality = 'high';
  g.drawImage(img, 0, 0, w, h);
  const d = g.getImageData(0, 0, w, h).data;
  // Ink = dark and opaque. The source is black-on-light artwork, so
  // luminance below the midpoint with real alpha is the mark itself.
  const bits = [];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const i = (y * w + x) * 4;
      const a = d[i + 3];
      const lum = (d[i] * 299 + d[i + 1] * 587 + d[i + 2] * 114) / 1000;
      bits.push(a > 128 && lum < 128 ? 1 : 0);
    }
  }
  return { w, h, bits, srcW: img.naturalWidth, srcH: img.naturalHeight };
}, { dataUrl: 'data:image/png;base64,' + b64, targetW });

await browser.close();

const { w, h, bits } = res;
const stride = Math.ceil(w / 8);
const bytes = new Uint8Array(stride * h);
for (let y = 0; y < h; y++) {
  for (let x = 0; x < w; x++) {
    if (bits[y * w + x]) bytes[y * stride + (x >> 3)] |= 0x80 >> (x & 7);
  }
}

let ink = 0;
for (const b of bits) ink += b;

const lines = [];
lines.push('// Generated by tools/mkbitmap.mjs from ' + src.split(/[\\/]/).pop() + '.');
lines.push('// Do not edit by hand; re-run the tool if the artwork changes.');
lines.push('//');
lines.push(`// Source ${res.srcW}x${res.srcH}, rendered to ${w}x${h}, 1 bit per pixel,`);
lines.push(`// MSB first, ${stride} bytes per row. ${ink} ink pixels.`);
lines.push('#pragma once');
lines.push('#include <stdint.h>');
lines.push('');
lines.push(`#define ${name}_W ${w}`);
lines.push(`#define ${name}_H ${h}`);
lines.push(`#define ${name}_STRIDE ${stride}`);
lines.push('');
lines.push(`static const uint8_t ${name}[${stride * h}] = {`);
for (let y = 0; y < h; y++) {
  const row = [];
  for (let i = 0; i < stride; i++) row.push('0x' + bytes[y * stride + i].toString(16).padStart(2, '0'));
  lines.push('    ' + row.join(', ') + ',');
}
lines.push('};');
writeFileSync(out, lines.join('\n') + '\n');
console.log(`${out}: ${w}x${h}, ${stride * h} bytes, ${ink} ink pixels`);
