// Bake a PNG's alpha into an 8-bit coverage map for the firmware.
import Foundation
import AppKit

let src = CommandLine.arguments[1]
let out = CommandLine.arguments[2]
let name = CommandLine.arguments[3]
let N = Int(CommandLine.arguments[4])!

guard let img = NSImage(contentsOfFile: src),
      let tiff = img.tiffRepresentation,
      let rep = NSBitmapImageRep(data: tiff),
      let cg = rep.cgImage else { fatalError("cannot read \(src)") }

// Read the source at full resolution into RGBA.
let w = cg.width, h = cg.height
var px = [UInt8](repeating: 0, count: w * h * 4)
px.withUnsafeMutableBytes { raw in
  let ctx = CGContext(data: raw.baseAddress, width: w, height: h, bitsPerComponent: 8,
                      bytesPerRow: w * 4, space: CGColorSpaceCreateDeviceRGB(),
                      bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue)!
  ctx.draw(cg, in: CGRect(x: 0, y: 0, width: w, height: h))
}

/* Ink coverage. The mark is a dark shape on transparency, so coverage is the
 * alpha - but a flattened white-background export would have none, so fall
 * back to darkness when the file turns out to be opaque. */
var anyAlpha = false
for i in stride(from: 3, to: px.count, by: 4) where px[i] < 250 { anyAlpha = true; break }
func cover(_ x: Int, _ y: Int) -> Double {
  let o = (y * w + x) * 4
  if anyAlpha { return Double(px[o + 3]) / 255.0 }
  let lum = (Double(px[o]) * 0.299 + Double(px[o+1]) * 0.587 + Double(px[o+2]) * 0.114) / 255.0
  return 1.0 - lum
}

// Trim to the mark's own bounding box so the baked map has no dead margin.
var x0 = w, y0 = h, x1 = -1, y1 = -1
for y in 0..<h { for x in 0..<w where cover(x, y) > 0.5 {
  if x < x0 { x0 = x }; if x > x1 { x1 = x }
  if y < y0 { y0 = y }; if y > y1 { y1 = y }
} }
let bw = x1 - x0 + 1, bh = y1 - y0 + 1
let side = max(bw, bh)
let ox = x0 - (side - bw) / 2, oy = y0 - (side - bh) / 2

// Box-filter down to N x N.
var cov = [UInt8](repeating: 0, count: N * N)
for ty in 0..<N {
  for tx in 0..<N {
    let sx0 = ox + side * tx / N, sx1 = ox + side * (tx + 1) / N
    let sy0 = oy + side * ty / N, sy1 = oy + side * (ty + 1) / N
    var sum = 0.0, n = 0
    for sy in sy0..<max(sy0 + 1, sy1) {
      for sx in sx0..<max(sx0 + 1, sx1) {
        if sx < 0 || sy < 0 || sx >= w || sy >= h { n += 1; continue }
        sum += cover(sx, sy); n += 1
      }
    }
    cov[ty * N + tx] = UInt8(max(0, min(255, Int((sum / Double(max(1, n))) * 255.0 + 0.5))))
  }
}

var s = """
// Generated by tools/mklogo.swift from \(URL(fileURLWithPath: src).lastPathComponent).
// Do not edit by hand.
//
// The studio's mark, as \(N)x\(N) of 8-bit coverage: 0 where the page shows
// through, 255 where the ink is solid, and the real numbers along every curve.
// Sampled bilinearly at draw time, so one map is sharp at the boot screen's
// 124 px and at the ABOUT row's 34.
#pragma once
#include <stdint.h>

#define \(name)_N \(N)
static const uint8_t \(name)[\(N) * \(N)] = {
"""
for i in 0..<(N * N) {
  if i % 16 == 0 { s += "\n    " }
  s += String(format: "0x%02x,", cov[i])
}
s += "\n};\n"
try! s.write(toFile: out, atomically: true, encoding: .utf8)
FileHandle.standardError.write("[mklogo] \(name) \(N)x\(N) from \(bw)x\(bh) box\n".data(using: .utf8)!)
